name: lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Lint
      run: npm run lint -- --env=commonjs
    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

