name: lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Lint
      run: npm run lint -- --env=commonjs
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: e2e tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000
